spring:
  application:
    name: madang

  datasource:
    url: jdbc:mariadb://localhost/madang_spring
    username: root
    password: green502

      # 주석은 똑같다.
mybatis:
  mapper-locations: mappers/**/*.xml



springdoc:
  swagger-ui:
    defaultModelExpandDepth: 10
    display-request-duration: true
    operations-shorter: method
    path: /swagger